AWSTemplateFormatVersion: 2010-09-09
Description: >
  Deployment bucket to store Lambda code and CloudFormation packages

Parameters:
  YourName:
    Type: String
    Description: Prefix for bucket name
    Default: ana-lattex

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${YourName}-deployment-bucket'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${YourName}-deployment-bucket'

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeploymentBucket
      PolicyDocument:
        Statement:
          - Sid: "AllowSSLRequestsOnly"
            Action: "s3:*"
            Principal: "*"
            Effect: "Deny"
            Resource:
              - !Sub "arn:aws:s3:::${YourName}-deployment-bucket"
              - !Sub "arn:aws:s3:::${YourName}-deployment-bucket/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"
AWSTemplateFormatVersion: 2010-09-09
Description: >
  Deployment bucket to store Lambda code and CloudFormation packages For Ana-Lattex Super Cafe Project

Parameters:
  TeamName:
    Type: String
    Description: Prefix for bucket name
    Default: ana-lattex-SC

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${TeamName}-deployment-bucket'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${TeamName}-deployment-bucket'

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeploymentBucket
      PolicyDocument:
        Statement:
          - Sid: "AllowSSLRequestsOnly"
            Action: "s3:*"
            Principal: "*"
            Effect: "Deny"
            Resource:
              - !Sub "arn:aws:s3:::${TeamName}-deployment-bucket"
              - !Sub "arn:aws:s3:::${TeamName}-deployment-bucket/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"
