version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  pgdata:


