AWSTemplateFormatVersion: 2010-09-09
Description: >
  ana-lattex S3 CloudFormation template for Phase 1 of ETL project

Parameters:
  TeamName:
    Type: String
    Description: Enter your team name to customise resource names
    Default: ana-lattex

Resources:
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${TeamName}-etl-pipeline'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: !Sub '${TeamName}-etl-pipeline'
        - Key: Project
          Value: ETL

  RawDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RawDataBucket
      PolicyDocument:
        Statement:
          - Sid: "AllowSSLRequestsOnly"
            Action: "s3:*"
            Principal: "*"
            Effect: "Deny"
            Resource:
              - !Sub "arn:aws:s3:::${TeamName}-etl-pipeline"
              - !Sub "arn:aws:s3:::${TeamName}-etl-pipeline/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"
